// Auto-generated from config.toml by hibikilogy-config Vite plugin.
// DO NOT EDIT.

export const HIBIKILOGY_CONFIG = {
  baseUrl: 'https://hibikilogy.vercel.app',
  title: '京吹学报 (Dev Preview)',
  description: '吹学著作集锦',
  defaultLanguage: 'zh',
  compileSass: true,
  minifyHtml: true,
  generateFeeds: true,
  generateSitemap: true,
  buildSearchIndex: true,
  hardLinkStatic: true,
  searchIndexFormat: 'fuse_json',
  searchIncludeTitle: true,
  searchIncludeDescription: true,
  searchIncludePath: true,
  searchIncludeDate: true,
  searchIncludeAuthor: true,
  searchIncludeContent: true,
  searchTruncateContentLength: 12000,
  markdownRenderEmoji: true,
  markdownExternalLinksTargetBlank: true,
  markdownExternalLinksNoFollow: true,
  markdownExternalLinksNoReferrer: true,
  markdownBottomFootnotes: true,
  markdownLazyAsyncImage: false,
  markdownGithubAlerts: true,
  markdownSmartPunctuation: false,
  markdownInsertAnchorLinks: 'left',
  markdownHighlightingErrorOnMissingLanguage: false,
  markdownHighlightingStyle: 'class',
  markdownHighlightingLightTheme: 'one-light',
  markdownHighlightingDarkTheme: 'one-dark-pro',
  slugifyAnchors: 'on',
  slugifyPaths: 'on',
  slugifyTaxonomies: 'on',
  themeColor: '#ffffff',
  twitterCard: 'summary_large_image',
  searchPageSize: 12,
  searchDefaultAuthor: '京吹学报',
  metaKeywords: '吹学, 吹响吧！上低音号, 京吹, 京吹学报',
  navbarLogo: '/logo.svg',
  defaultCover: '/imgs/tags.svg',
  imageHostRewriteOldHost: 'https://hibikilogy.vercel.app/',
  imageHostRewriteNewHost: 'https://hibikilogy.interknot.site/',
  faviconAppleTouchIcon: '/apple-touch-icon-precomposed.png',
  faviconSmallIcon: '/favicon.ico',
  faviconSvgIcon: '/logo-blue.svg',
  faviconSafariPinnedTab: '/apple-touch-icon-precomposed.png',
  faviconWebmanifest: '/site.manifest',
  analyticsGoogle: 'G-DWY77Z5HMS',
} as const

export const HIBIKILOGY_TRANSLATIONS = {
  searchPlaceholder: '搜索',
  searchSubmitText: '搜索',
  searchRelatedTags: '相关标签',
  authorLabel: '作者',
  authorTitle: '作者',
  publishPrefix: '发布于',
  dateFormat: '%Y 年 %m 月 %d 日',
  paginationAria: '分页',
  paginationPagePrefix: '第',
  paginationPageMiddle: '页 / 共',
  paginationPageSuffix: '页',
  paginationPrev: '上一页',
  paginationNext: '下一页',
  sortRelevance: '相关度排序',
  sortTitleAsc: '文章标题正序',
  sortDateAsc: '发布日期正序',
  tagsTitle: '标签',
  tagsCountSuffix: '个标签',
  relatedArticlesSuffix: '篇相关文章',
  notFoundTitle: '404 Not Found',
  tagCategoryPeople: '人物',
  tagCategorySection: '版块',
  tagCategoryMisc: '杂类',
  searchClear: '清空',
  searchIndexLoading: '正在加载索引数据中',
  searchCacheReading: '正在读取搜索序列化索引缓存中',
  searchIndexBuilding: '正在构建搜索序列化索引数据中',
  searchLoading: '正在搜索「{0}」',
  searchFailed: '搜索失败',
  searchFailedWithError: '搜索失败：{0}',
  searchEmpty: '没有找到与「{0}」相关的搜索结果',
  searchFound: '共找到 {0} 条与「{1}」相关的结果',
  searchIdle: '当前共 {0} 篇文章',
} as const
