version = 1

[url.image_cdn]
from = [ "https://hibikilogy.vercel.app/" ]
to = "https://hibikilogy.interknot.site/"
relative_to = "target-root"
exclude_extensions = [
  "svg",
  "gif"
]

[html]
files = [
  "**/*.html",
  "!search-articles/index.html",
]

[[html.rules]]
name = "image-urls"
select = "img, lazy-image"
rewrite_urls = { map = "image_cdn", attributes = [
  "src",
  "srcset",
  "data-srcset"
] }

[[html.rules]]
name = "article-images"
select = ".content-container img"
asset = { type = "image", from = [
  "src",
  "srcset",
  "data-srcset"
] }
set = { zoomable = "true" }
metadata = { thumbhash = "thumbhash", width = "width", height = "height" }
replace_tag = "lazy-image"

[[html.rules]]
name = "lazy-image-metadata"
select = "lazy-image"
asset = { type = "image", from = [
  "src",
  "srcset",
  "data-srcset"
] }
metadata = { thumbhash = "thumbhash", width = "width", height = "height" }

[[json]]
name = "search-cover"
sources = [
  { files = [ "**/*.html" ], select = 'script#hibikilogy-search-articles-data[type="application/json"]' },
  { files = [ "search-articles/index.html" ] },
]
each = "object-values"
rewrite_url = { field = "cs", map = "image_cdn" }
asset = { type = "image", from = "cs" }
metadata = { thumbhash = "ct", width = "cw", height = "ch" }
