use anyhow::{anyhow, Context, Result};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CssUnicodeRanges {
    ranges: Vec<(u32, u32)>,
}

impl CssUnicodeRanges {
    pub fn parse(css: &str) -> Result<Self> {
        let mut ranges = Vec::new();
        let mut cursor = 0;

        while let Some(offset) = css[cursor..].find("unicode-range:") {
            let start = cursor + offset + "unicode-range:".len();
            let Some(end_offset) = css[start..].find(';') else {
                return Err(anyhow!("unterminated unicode-range declaration"));
            };
            let declaration = &css[start..start + end_offset];
            parse_unicode_range_declaration(declaration, &mut ranges)?;
            cursor = start + end_offset + 1;
        }

        Ok(Self {
            ranges: merge_ranges(ranges),
        })
    }

    pub fn contains(&self, codepoint: u32) -> bool {
        self.ranges
            .binary_search_by(|&(start, end)| {
                if codepoint < start {
                    std::cmp::Ordering::Greater
                } else if codepoint > end {
                    std::cmp::Ordering::Less
                } else {
                    std::cmp::Ordering::Equal
                }
            })
            .is_ok()
    }
}

pub fn filter_uncovered_codepoints(
    codepoints: impl IntoIterator<Item = u32>,
    covered: &CssUnicodeRanges,
) -> Vec<u32> {
    let mut uncovered: Vec<u32> = codepoints
        .into_iter()
        .filter(|&codepoint| !covered.contains(codepoint))
        .collect();
    uncovered.sort_unstable();
    uncovered.dedup();
    uncovered
}

pub fn write_comment_only_css(generator_name: &str, message: &str) -> String {
    format!("/* Generated by {generator_name}. {message} */\n")
}

fn parse_unicode_range_declaration(declaration: &str, ranges: &mut Vec<(u32, u32)>) -> Result<()> {
    for token in declaration.split(',') {
        let token = token.trim();
        if token.is_empty() {
            continue;
        }

        let token = token
            .strip_prefix("U+")
            .or_else(|| token.strip_prefix("u+"))
            .ok_or_else(|| anyhow!("invalid unicode-range token: {token}"))?;

        let (start, end) = if let Some((start, end)) = token.split_once('-') {
            (parse_hex(start)?, parse_hex(end)?)
        } else {
            let value = parse_hex(token)?;
            (value, value)
        };

        if start > end {
            return Err(anyhow!("invalid unicode-range token: U+{token}"));
        }

        ranges.push((start, end));
    }

    Ok(())
}

fn parse_hex(value: &str) -> Result<u32> {
    u32::from_str_radix(value.trim(), 16)
        .with_context(|| format!("failed to parse unicode codepoint {value}"))
}

fn merge_ranges(mut ranges: Vec<(u32, u32)>) -> Vec<(u32, u32)> {
    if ranges.is_empty() {
        return ranges;
    }

    ranges.sort_unstable_by_key(|&(start, _)| start);
    let mut merged = Vec::with_capacity(ranges.len());
    let mut current = ranges[0];

    for (start, end) in ranges.into_iter().skip(1) {
        if start <= current.1.saturating_add(1) {
            current.1 = current.1.max(end);
        } else {
            merged.push(current);
            current = (start, end);
        }
    }

    merged.push(current);
    merged
}
