use anyhow::{anyhow, Context, Result};
use skera::{subset_font, Plan, SubsetFlags};
use std::fs;
use std::path::{Component, Path, PathBuf};
use write_fonts::read::{
    collections::IntSet,
    types::{NameId, Tag},
    FontRef,
};

pub const HASH_HEX_LEN: usize = 16;

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct CleanupReport {
    pub removed: Vec<String>,
    pub skipped: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FontFaceDescriptors {
    pub style: Option<&'static str>,
    pub weight: Option<&'static str>,
}

impl FontFaceDescriptors {
    #[allow(dead_code)]
    pub const PLAIN: Self = Self {
        style: None,
        weight: None,
    };

    #[allow(dead_code)]
    pub const VARIABLE: Self = Self {
        style: Some("normal"),
        weight: Some("200 900"),
    };
}

pub fn subset_with_skera(font_data: &[u8], codepoints: &[u32]) -> Result<Vec<u8>> {
    let font = FontRef::new(font_data).context("failed to parse input font")?;
    let unicodes = codepoints.iter().copied().collect::<IntSet<u32>>();
    let gids = IntSet::empty();
    let drop_tables = IntSet::<Tag>::empty();
    let layout_scripts = inverted_set::<Tag>();
    let layout_features = inverted_set::<Tag>();
    let name_ids = inverted_set::<NameId>();
    let name_languages = inverted_set::<u16>();
    let flags = SubsetFlags::SUBSET_FLAGS_PASSTHROUGH_UNRECOGNIZED
        | SubsetFlags::SUBSET_FLAGS_GLYPH_NAMES
        | SubsetFlags::SUBSET_FLAGS_NOTDEF_OUTLINE
        | SubsetFlags::SUBSET_FLAGS_RETAIN_GIDS;

    let plan = Plan::new(
        &gids,
        &unicodes,
        &font,
        flags,
        &drop_tables,
        &layout_scripts,
        &layout_features,
        &name_ids,
        &name_languages,
    );

    subset_font(&font, &plan).map_err(|error| anyhow!("skera subset failed: {error}"))
}

pub fn hashed_output_file_name(file_name: &str, bytes: &[u8]) -> String {
    let hash = fnv1a64(bytes);
    let (stem, extension) = split_file_name(file_name);
    format!("{stem}.{hash:0width$x}.{extension}", width = HASH_HEX_LEN)
}

pub fn remove_old_font_outputs(
    output_dir: &Path,
    template_file: &str,
    keep_file: Option<&str>,
) -> Result<CleanupReport> {
    let (stem, extension) = split_file_name(template_file);
    let mut report = CleanupReport::default();

    for entry in fs::read_dir(output_dir)
        .with_context(|| format!("failed to read {}", output_dir.display()))?
    {
        let entry = entry.with_context(|| format!("failed to read {}", output_dir.display()))?;
        if !entry.file_type()?.is_file() {
            continue;
        }

        let file_name = entry.file_name();
        let file_name = file_name.to_string_lossy();
        if keep_file.is_some_and(|keep| file_name == keep) {
            continue;
        }

        let matches_hashed = file_name.starts_with(&format!("{stem}."))
            && file_name.ends_with(&format!(".{extension}"));
        let matches_plain = file_name == template_file;
        if !matches_hashed && !matches_plain {
            continue;
        }

        match fs::remove_file(entry.path()) {
            Ok(()) => report.removed.push(file_name.into_owned()),
            Err(error) if error.kind() == std::io::ErrorKind::PermissionDenied => {
                report.skipped.push(file_name.into_owned());
            }
            Err(error) => {
                return Err(error)
                    .with_context(|| format!("failed to remove {}", entry.path().display()));
            }
        }
    }

    report.removed.sort();
    report.skipped.sort();
    Ok(report)
}

pub fn write_font_css(
    generator_name: &str,
    font_family: &str,
    font_url: &str,
    codepoints: &[u32],
    font_display: &str,
    descriptors: FontFaceDescriptors,
) -> String {
    let mut css = format!("/* Generated by {generator_name}. Do not edit by hand. */\n\n");
    css.push_str("@font-face {\n");
    css.push_str(&format!(
        "  font-family: \"{}\";\n",
        escape_css_string(font_family)
    ));
    if let Some(style) = descriptors.style {
        css.push_str(&format!("  font-style: {};\n", style));
    }
    if let Some(weight) = descriptors.weight {
        css.push_str(&format!("  font-weight: {};\n", weight));
    }
    css.push_str(&format!("  font-display: {};\n", font_display));
    css.push_str(&format!(
        "  src: url(\"{}\") format(\"woff2\");\n",
        escape_css_string(font_url)
    ));
    css.push_str(&format!(
        "  unicode-range: {};\n",
        css_unicode_range(codepoints)
    ));
    css.push_str("}\n");
    css
}

pub fn font_url_for_css(css_output_dir: &Path, font_path: &Path) -> Result<String> {
    let relative = relative_path(css_output_dir, font_path).ok_or_else(|| {
        anyhow!(
            "failed to compute relative font path from {} to {}",
            css_output_dir.display(),
            font_path.display()
        )
    })?;

    Ok(relative
        .components()
        .map(component_to_url_segment)
        .collect::<Vec<_>>()
        .join("/"))
}

fn inverted_set<T>() -> IntSet<T>
where
    T: Clone + Eq + std::hash::Hash,
{
    let mut set = IntSet::<T>::empty();
    set.invert();
    set
}

fn split_file_name(file_name: &str) -> (&str, &str) {
    file_name.rsplit_once('.').unwrap_or((file_name, "woff2"))
}

fn fnv1a64(bytes: &[u8]) -> u64 {
    let mut hash = 0xcbf29ce484222325_u64;
    for byte in bytes {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    hash
}

fn css_unicode_range(codepoints: &[u32]) -> String {
    if codepoints.is_empty() {
        return "U+0-10FFFF".to_string();
    }

    let mut ranges = Vec::new();
    let mut start = codepoints[0];
    let mut previous = codepoints[0];

    for &codepoint in &codepoints[1..] {
        if codepoint == previous + 1 {
            previous = codepoint;
            continue;
        }

        ranges.push(format_range(start, previous));
        start = codepoint;
        previous = codepoint;
    }

    ranges.push(format_range(start, previous));
    ranges.join(", ")
}

fn format_range(start: u32, end: u32) -> String {
    if start == end {
        format!("U+{:04X}", start)
    } else {
        format!("U+{:04X}-{:04X}", start, end)
    }
}

fn escape_css_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn component_to_url_segment(component: Component<'_>) -> String {
    match component {
        Component::ParentDir => "..".to_string(),
        Component::CurDir => ".".to_string(),
        Component::Normal(value) => value.to_string_lossy().into_owned(),
        Component::RootDir => "/".to_string(),
        Component::Prefix(prefix) => prefix.as_os_str().to_string_lossy().into_owned(),
    }
}

fn relative_path(from_dir: &Path, to_path: &Path) -> Option<PathBuf> {
    let from_components: Vec<_> = from_dir.components().collect();
    let to_components: Vec<_> = to_path.components().collect();

    let mut shared_len = 0;
    while shared_len < from_components.len()
        && shared_len < to_components.len()
        && from_components[shared_len] == to_components[shared_len]
    {
        shared_len += 1;
    }

    if shared_len == 0 && from_dir.is_absolute() != to_path.is_absolute() {
        return None;
    }

    let mut relative = PathBuf::new();
    for _ in shared_len..from_components.len() {
        relative.push("..");
    }
    for component in &to_components[shared_len..] {
        relative.push(component.as_os_str());
    }

    if relative.as_os_str().is_empty() {
        relative.push(".");
    }

    Some(relative)
}
