name: LINKS

on:
  push:
    branches:
      - dev
      - next
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - dev
      - next
      - main
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '00 18 * * *'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
