# @See https://pages.github.com/
name: GITHUB_PAGE

on:
  # trigger deployment on every push to main branch
  push:
    branches:
      - main
    # @See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
    paths-ignore:
      - './README.md'
  # trigger deployment manually
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - name: Build site
        uses: shalzz/zola-deploy-action@v0.19.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # choose node.js version to use
          node-version: '18'

      - name: chown
        run: echo "$(whoami):$(id -gn)" | xargs -I {} sudo chown -R {} public

      - name: Run Pagefind
        run: npm_config_yes=true npx pagefind --source "public"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

          # please check out the docs of the workflow for more details
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # deploy to gh-pages branch
          target_branch: gh-pages
          # deploy the default output dir of VuePress
          build_dir: public
        env:
          # @see https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
